### ISSUE TITLE
null @name referenced?

### ISSUE THREAD

**Issue by akonsu** [noflo/noflo-indexeddb#1]
this code sets `@name` to `null`: https://github.com/noflo/noflo-indexeddb/blob/fef1bcbb63dc7333d6960c9620403f2fb5e0ebd1/components/Open.coffee#L25

after that, this code, uses `@name` (`null` effectively) as the group's name: https://github.com/noflo/noflo-indexeddb/blob/fef1bcbb63dc7333d6960c9620403f2fb5e0ebd1/components/Open.coffee#L29

should it read

```
    name = @name
    @name = null
    version = @version
    @version = null
    req.onupgradeneeded = (e) =>
      @outPorts.upgrade.beginGroup name
```

**Comment by bergie** [comment]
Fixed via #42
